### ISSUE TITLE
Suggest nano?

### ISSUE THREAD

**Issue by RichardBH** [tomcam/py4webcasts#2]
I know this is a contentious issue, but how about suggesting some other editors like nano, which are much more intuitive to newbies...
https://github.com/tomcam/py4webcasts/blob/master/docs/how-install-source-pythonanywhere.md#update-bottle_apppy

**Comment by mdipierro** [comment]
On linux I very much like the jed. It is text only. has syntax highlighting and can emulate emacs. I had good feedback from students.

**Comment by RichardBH** [comment]
Jed looks good, but I just had a look at how to install it and gave up. (I'm a perfect guinea pig as the guy who knows just enough to scrape by regarding linux, web development etc.) I always wanted to learn EMACS and VIM, but the learning curve is high, and generally in the command line I'm just doing small edits anyway. (Far too many other things to learn as a priority. :)

**Comment by mdipierro** [comment]
On ubuntu you just do

sudo apt-get install jed

On window I have no idea.

How about vscode?

**Comment by RichardBH** [comment]
Ok, I just tried Jed on a Ubuntu VM and I really like it. Thats my new nano 👍 

I think this edit is just in a pythonanywhere bash console to update the bottle.py. So we could probably just change the steps to use the python anywhere graphical editor if required.
Or find a way to install jed in pythonanywhere.

Thanks for putting me onto Jed!

**Comment by mdipierro** [comment]
:-)

**Comment by tomcam** [comment]
Discussed this previously with Massimo and we decided that VS Code makes the most sense because it's the same on all platforms, free, and everyone's second favorite editor. This will have the super important side effect of making the videos look roughly right whether you're on Windows, Linux, or MacOS.

Obviously the RIGHT answer is neovim/vim/emacs/jed/nano/vi/ (and we all know that neovim is the right answer ;) but sometimes second best is the optimum solution.

I will probably leave this line because it's pretty open-ended.

```
# Replace vim with whatever editor you prefer
vim ~/py4web/bottle_app.py
```
